# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Financial CLM (Causal Language Modeling) Dataset for decoder-only pretraining.

Reads text corpus lines generated by the tokenizer pipeline and produces
(input_ids, labels) pairs for next-token prediction. No masking logic is
needed -- every token position provides a training signal.

Corpus line format:
    <bos> AMT_3 MERCH_1498 ... <sep> AMT_1 MERCH_42 ... <eos>

For causal LM:
    input_ids = full token sequence
    labels    = same as input_ids, with <pad> positions set to -100
                (HuggingFace convention: -100 = ignore in loss)

The model's forward pass handles the internal shift: it predicts
position i+1 from position i.

NeMo AutoModel Integration
--------------------------
Referenced in YAML via file-path:function ``_target_`` syntax::

    dataset:
      _target_: transaction_model.training.clm_data:build_financial_clm_dataset
      data_path: /path/to/train_corpus.txt
      seq_length: 4096

NeMo AutoModel resolves the ``_target_``, calls ``build_financial_clm_dataset()``
with the remaining keys as kwargs, and wraps the returned Dataset in a
``StatefulDataLoader``.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List, Optional, Union

import numpy as np
import torch
from torch.utils.data import Dataset

# Ensure transaction_model package root is importable when loaded by NeMo's
# file-path _target_ resolution (which bypasses normal package imports).
_pkg_root = str(Path(__file__).resolve().parent.parent.parent)
if _pkg_root not in sys.path:
    sys.path.insert(0, _pkg_root)


class FinancialCLMDataset(Dataset):
    """PyTorch Dataset for causal language modeling on financial transactions.

    Compatible with NeMo AutoModel's ``StatefulDataLoader`` — returns dicts
    with ``input_ids`` and ``labels`` tensors, matching the interface expected
    by ``MaskedCrossEntropy`` loss and HuggingFace causal LM forward().
    """

    def __init__(
        self,
        sequences: List[List[int]],
        seq_length: int = 4096,
        pad_token_id: int = 0,
    ):
        self.sequences = sequences
        self.seq_length = seq_length
        self.pad_token_id = pad_token_id

    def __len__(self) -> int:
        return len(self.sequences)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        tokens = self.sequences[idx]

        if len(tokens) > self.seq_length:
            tokens = tokens[: self.seq_length]

        input_ids = np.full(self.seq_length, self.pad_token_id, dtype=np.int64)
        input_ids[: len(tokens)] = tokens

        labels = np.full(self.seq_length, -100, dtype=np.int64)
        labels[: len(tokens)] = tokens

        return {
            "input_ids": torch.from_numpy(input_ids),
            "labels": torch.from_numpy(labels),
        }


def load_corpus_and_tokenize(
    data_path: Union[str, Path],
    merchant_hash_size: int = 2000,
    seq_length: int = 4096,
    tokenizer_variant: str = "tabformer",
    tokenizer_state_path: Optional[str] = None,
) -> FinancialCLMDataset:
    """Load a text corpus file and build a FinancialCLMDataset.

    Each line in the corpus is a space-separated token string like:
        <bos> AMT_3 MERCH_1498 CAT_RETAIL ... <sep> AMT_1 ... <eos>

    Parameters
    ----------
    data_path : str | Path
        Corpus text file path (one sequence per line).
    merchant_hash_size : int
        TabFormer 路线的商户 hash 大小（仅 variant="tabformer" 使用）。
    seq_length : int
        Padding / truncation length per sequence.
    tokenizer_variant : {"tabformer", "yl"}
        "tabformer"（默认）→ FinancialTabularTokenizer（静态词表）；
        "yl" → YLTabularTokenizer，必须配合已 fit 保存的 state 文件
        （tokenizer_state_path）使用。
    tokenizer_state_path : str, optional
        variant="yl" 时必填：上一阶段 ``YLTabularTokenizer.save`` 输出的 JSON
        路径。对应 ``configs/dataset_yl.yaml::tokenizer.state_path``。
    """
    tokenizer = _build_tokenizer(
        variant=tokenizer_variant,
        merchant_hash_size=merchant_hash_size,
        tokenizer_state_path=tokenizer_state_path,
    )

    data_path = Path(data_path)
    print(f"Loading corpus from {data_path} (variant={tokenizer_variant})...")

    sequences = []
    with open(data_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            token_ids = tokenizer.encode(line, max_length=seq_length)
            sequences.append(token_ids)

    print(f"  Loaded {len(sequences):,} sequences (seq_length={seq_length}, "
          f"vocab_size={tokenizer.get_vocab_size()})")

    return FinancialCLMDataset(
        sequences=sequences,
        seq_length=seq_length,
        pad_token_id=tokenizer.pad_token_id,
    )


def _build_tokenizer(
    variant: str,
    merchant_hash_size: int = 2000,
    tokenizer_state_path: Optional[str] = None,
):
    """按 variant 选择 tokenizer（TabFormer 静态 / YL 已 fit state）。"""
    if variant == "tabformer":
        from transaction_model.tokenizer.financial_tokenizer import (
            FinancialTabularTokenizer,
        )

        return FinancialTabularTokenizer(
            merchant_hash_size=merchant_hash_size,
            category_hierarchy=True,
            temporal_encoding=True,
        )

    if variant == "yl":
        if tokenizer_state_path is None:
            raise ValueError(
                "tokenizer_variant='yl' requires tokenizer_state_path "
                "(point it at configs/dataset_yl.yaml::tokenizer.state_path)"
            )
        from transaction_model.tokenizer.yl_tokenizer import YLTabularTokenizer

        return YLTabularTokenizer.from_file(tokenizer_state_path)

    raise ValueError(
        f"Unknown tokenizer_variant: {variant!r}. "
        f"Expected 'tabformer' or 'yl'."
    )


def build_financial_clm_dataset(
    data_path: str,
    merchant_hash_size: int = 2000,
    seq_length: int = 4096,
    tokenizer_variant: str = "tabformer",
    tokenizer_state_path: Optional[str] = None,
    **kwargs,
) -> FinancialCLMDataset:
    """Entry point for NeMo AutoModel YAML config.

    This function is called by the recipe when it resolves the dataset
    ``_target_``. Any extra keys in the YAML dataset section are passed
    as ``**kwargs`` and silently ignored, ensuring forward compatibility
    with new config keys.

    Pass ``tokenizer_variant: "yl"`` and ``tokenizer_state_path`` in the
    YAML dataset section to train on YL (银联) corpus.
    """
    return load_corpus_and_tokenize(
        data_path=data_path,
        merchant_hash_size=merchant_hash_size,
        seq_length=seq_length,
        tokenizer_variant=tokenizer_variant,
        tokenizer_state_path=tokenizer_state_path,
    )
